### ISSUE TITLE
radio support

### ISSUE THREAD

**Issue by whaleygeek** [whaleygeek/bitio#17]
The micro:bit has a radio module. I'd like to be able to, on the host machine, do this

import radio
radio.on()
radio.send('hello world')

I'd also like to be able to change the radio group and change the radio channel.

I'd also like to be able to set up a tight loop that notifies via a function when an incoming radio message arrives. I'd like a way to do this whereby the poll time of bitio is not too critical, so that messages are not lost.

I'd like to be able to run multiple instances of bitio connected to different micro:bits each tuned to different channels or listening on different groups, so that I can build multi-channel projects.

**Comment by whaleygeek** [comment]
Similar 'module' issues need resolving as per https://github.com/whaleygeek/bitio/issues/16

**Comment by whaleygeek** [comment]
Dependent on work being done by: https://github.com/whaleygeek/bitio/issues/11 for the multi-micro:bit work

**Comment by robmarkcole** [comment]
Is it a 433MHz radio? Lots of projects on e.g hackster make use of this and would be nice to setup the microbit as a general purpose receiver/transmitter

**Comment by whaleygeek** [comment]
The radio on the micro:bit uses the onboard Bluetooth hardware. It's the Nordic Gazel protocol, so it's at 2.4GHz - it's the super simple same radio interface you get in both python.microbit.org and makecode.microbit.org

**Comment by whaleygeek** [comment]
Fixed by https://github.com/whaleygeek/bitio/commit/a6eae579057a943f3613aea551620cc4a69f48cf
