### ISSUE TITLE
Feature proposal : set serial port via environment variable

### ISSUE THREAD

**Issue by bcopy** [whaleygeek/bitio#40]
AFAIK, the only way to bypass the port scan upon startup is to create a ```portscan.cache``` file.
It would be helpful to be able to use an environment variable to the same effect.

**Comment by musabkilic** [comment]
I can work on this if you like the idea @whaleygeek

-------- Original Message --------

**Comment by whaleygeek** [comment]
Sounds like a good idea @musabkilic go for it!!!

**Comment by whaleygeek** [comment]
https://github.com/whaleygeek/bitio/commit/6f294fbd740177d513007e80adb690fcf1e0f123 fixes this request
