### ISSUE TITLE
ALL_CLOCKS

### ISSUE THREAD

**Issue by martinohanlon** [whaleygeek/bitio#8]
is missing, it would make working with clocks a lot easier if it was implemented

**Comment by DavidWhaleMEF** [comment]
Sure, I'll add it tomorrow.

It goes in the creational code here:

https://github.com/whaleygeek/bitio/blob/master/src/microbit/api.py#L155

**Comment by DavidWhaleMEF** [comment]
I will also add ALL_ARROWS as that is useful for building a compass.

**Comment by whaleygeek** [comment]
see #9

**Comment by whaleygeek** [comment]
Fixed by https://github.com/whaleygeek/bitio/commit/47854d82f7a4b7f5ee4c9cca6d7923ad196f7fd8
